### ISSUE TITLE
Minor UI typo in PAG about page: aggreating -> should be aggregating

### ISSUE THREAD

**Issue by acsr** [collective/pyf-gui#1]
Fixing this could improve SEO when searching for e.g. "aggregating Plone Add-ons"

https://pag.derico.tech/about

### About this service
We are _aggreating_ all Plone…

s/aggreating/aggregating

**Comment by stevepiercy** [comment]
This was fixed in https://github.com/collective/pyf-gui/pull/3, but the site needs to be deployed. Closing.
